//! Embedded SVG icons (HugeIcons, generated by `packaging/icons.mjs`) served to gpui / gpui-component via `AssetSource`.

use anyhow::Result;
use gpui::{AssetSource, SharedString};
use std::borrow::Cow;

#[derive(rust_embed::RustEmbed)]
#[folder = "assets"]
#[include = "icons/*.svg"]
#[include = "logos/*"]
pub struct Assets;

impl AssetSource for Assets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        Ok(Self::get(path).map(|f| f.data))
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        Ok(Self::iter()
            .filter(|p| p.starts_with(path))
            .map(|p| SharedString::from(p.to_string()))
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::Assets;
    use crate::views::settings::SettingsPage;
    use gpui_component::{IconName, IconNamed as _};
    use majik_generation::recovery::RecoveryAction;
    use majik_providers::asset::AssetRole;

    const MANIFEST: &str = include_str!("../../../packaging/icons.json");
    /// The OS-chrome glyphs gpui-component's title bar draws; kept as they are, not generated
    /// (see `assets/icons/README.md`).
    const CHROME: [&str; 5] = ["window-close", "window-minimize", "window-maximize", "window-restore", "resize-corner"];

    fn manifest_names() -> Vec<String> {
        let manifest: serde_json::Map<String, serde_json::Value> = serde_json::from_str(MANIFEST).expect("packaging/icons.json parses");
        manifest.keys().filter(|key| *key != "//").cloned().collect()
    }

    fn embedded(name: &str) -> bool {
        Assets::get(&format!("icons/{name}.svg")).is_some()
    }

    #[test]
    fn every_manifest_icon_is_embedded() {
        for name in manifest_names() {
            assert!(embedded(&name), "icons/{name}.svg is missing: run `node packaging/icons.mjs`");
        }
    }

    #[test]
    fn every_embedded_icon_is_in_the_manifest() {
        let names = manifest_names();
        for path in Assets::iter().filter(|path| path.starts_with("icons/") && path.ends_with(".svg")) {
            let name = path.trim_start_matches("icons/").trim_end_matches(".svg");
            assert!(names.iter().any(|known| known == name) || CHROME.contains(&name), "{path} is not in packaging/icons.json: add it there or delete the file");
        }
    }

    /// gpui-component's widgets (menus, pickers, the title bar on Windows/Linux, …) load these by
    /// fixed path, so the bundle must carry every one the library draws.
    #[test]
    fn gpui_component_icons_resolve() {
        let icons = [
            IconName::Asterisk,
            IconName::BookOpen,
            IconName::Calendar,
            IconName::CaseSensitive,
            IconName::Check,
            IconName::ChevronDown,
            IconName::ChevronLeft,
            IconName::ChevronRight,
            IconName::ChevronsUpDown,
            IconName::CircleCheck,
            IconName::CircleX,
            IconName::Close,
            IconName::Copy,
            IconName::Ellipsis,
            IconName::ExternalLink,
            IconName::Eye,
            IconName::EyeOff,
            IconName::Github,
            IconName::Inbox,
            IconName::Info,
            IconName::Inspector,
            IconName::Loader,
            IconName::Maximize,
            IconName::Minimize,
            IconName::Minus,
            IconName::PanelBottom,
            IconName::PanelBottomOpen,
            IconName::PanelLeft,
            IconName::PanelLeftClose,
            IconName::PanelLeftOpen,
            IconName::PanelRight,
            IconName::PanelRightClose,
            IconName::PanelRightOpen,
            IconName::Plus,
            IconName::Replace,
            IconName::ResizeCorner,
            IconName::Search,
            IconName::SortAscending,
            IconName::SortDescending,
            IconName::Star,
            IconName::StarFill,
            IconName::TriangleAlert,
            IconName::Undo2,
            IconName::User,
            IconName::WindowClose,
            IconName::WindowMaximize,
            IconName::WindowMinimize,
            IconName::WindowRestore,
        ];
        for icon in icons {
            let path = icon.path();
            assert!(Assets::get(&path).is_some(), "{path} is missing from the bundle");
        }
    }

    /// Icon names that reach `ui::icon` through an enum rather than a literal at the call site.
    #[test]
    fn role_recovery_and_settings_icons_resolve() {
        for role in AssetRole::ALL {
            assert!(embedded(role.icon()), "{role:?} → {}", role.icon());
        }
        for action in [RecoveryAction::Retry, RecoveryAction::OpenProviderSettings, RecoveryAction::CheckCredits(String::new())] {
            assert!(embedded(action.icon()), "{action:?} → {}", action.icon());
        }
        for page in SettingsPage::ALL {
            assert!(embedded(page.icon()), "{page:?} → {}", page.icon());
        }
    }
}
