//! Embedded SVG icons (HugeIcons, generated by `packaging/icons.mjs`) served to gpui / gpui-component via `AssetSource`.

use anyhow::Result;
use gpui::{AssetSource, SharedString};
use std::borrow::Cow;

#[derive(rust_embed::RustEmbed)]
#[folder = "assets"]
#[include = "icons/*.svg"]
#[include = "logos/*"]
pub struct Assets;

impl AssetSource for Assets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        Ok(Self::get(path).map(|f| f.data))
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        Ok(Self::iter()
            .filter(|p| p.starts_with(path))
            .map(|p| SharedString::from(p.to_string()))
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::Assets;
    use crate::composer_state::ComposeTab;
    use crate::views::settings::SettingsPage;
    use gpui_component::{IconName, IconNamed as _};
    use majik_generation::recovery::RecoveryAction;
    use majik_providers::asset::AssetRole;

    const MANIFEST: &str = include_str!("../../../packaging/icons.json");
    /// The OS-chrome glyphs gpui-component's title bar draws; kept as they are, not generated
    /// (see `assets/icons/README.md`).
    const CHROME: [&str; 5] = ["window-close", "window-minimize", "window-maximize", "window-restore", "resize-corner"];

    fn manifest_names() -> Vec<String> {
        let manifest: serde_json::Map<String, serde_json::Value> = serde_json::from_str(MANIFEST).expect("packaging/icons.json parses");
        manifest.keys().filter(|key| *key != "//").cloned().collect()
    }

    fn embedded(name: &str) -> bool {
        Assets::get(&format!("icons/{name}.svg")).is_some()
    }

    #[test]
    fn every_manifest_icon_is_embedded() {
        for name in manifest_names() {
            assert!(embedded(&name), "icons/{name}.svg is missing: run `node packaging/icons.mjs`");
        }
    }

    #[test]
    fn every_embedded_icon_is_in_the_manifest() {
        let names = manifest_names();
        for path in Assets::iter().filter(|path| path.starts_with("icons/") && path.ends_with(".svg")) {
            let name = path.trim_start_matches("icons/").trim_end_matches(".svg");
            assert!(names.iter().any(|known| known == name) || CHROME.contains(&name), "{path} is not in packaging/icons.json: add it there or delete the file");
        }
    }

    /// gpui-component's widgets (menus, pickers, the title bar on Windows/Linux, …) load these by
    /// fixed path, so the bundle must carry every one the library draws.
    #[test]
    fn gpui_component_icons_resolve() {
        let icons = [
            IconName::Asterisk,
            IconName::BookOpen,
            IconName::Calendar,
            IconName::CaseSensitive,
            IconName::Check,
            IconName::ChevronDown,
            IconName::ChevronLeft,
            IconName::ChevronRight,
            IconName::ChevronsUpDown,
            IconName::CircleCheck,
            IconName::CircleX,
            IconName::Close,
            IconName::Copy,
            IconName::Ellipsis,
            IconName::ExternalLink,
            IconName::Eye,
            IconName::EyeOff,
            IconName::Github,
            IconName::Inbox,
            IconName::Info,
            IconName::Inspector,
            IconName::Loader,
            IconName::Maximize,
            IconName::Minimize,
            IconName::Minus,
            IconName::PanelBottom,
            IconName::PanelBottomOpen,
            IconName::PanelLeft,
            IconName::PanelLeftClose,
            IconName::PanelLeftOpen,
            IconName::PanelRight,
            IconName::PanelRightClose,
            IconName::PanelRightOpen,
            IconName::Plus,
            IconName::Replace,
            IconName::ResizeCorner,
            IconName::Search,
            IconName::SortAscending,
            IconName::SortDescending,
            IconName::Star,
            IconName::StarFill,
            IconName::TriangleAlert,
            IconName::Undo2,
            IconName::User,
            IconName::WindowClose,
            IconName::WindowMaximize,
            IconName::WindowMinimize,
            IconName::WindowRestore,
        ];
        for icon in icons {
            let path = icon.path();
            assert!(Assets::get(&path).is_some(), "{path} is missing from the bundle");
        }
    }

    fn logo_svgs() -> Vec<(String, String)> {
        Assets::iter()
            .filter(|path| path.starts_with("logos/") && path.ends_with(".svg"))
            .map(|path| (path.to_string(), String::from_utf8(Assets::get(&path).expect("listed").data.into_owned()).expect("utf-8")))
            .collect()
    }

    /// Every model and provider names a logo, and `ui::logo` draws only an embedded SVG.
    #[test]
    fn every_catalog_and_provider_logo_is_embedded() {
        use majik_providers::catalog::{audio, image, tool, video};
        let mut names: Vec<&str> = Vec::new();
        names.extend(image::ALL.iter().map(|m| m.logo));
        names.extend(video::ALL.iter().map(|m| m.logo));
        names.extend(audio::ALL.iter().map(|m| m.logo));
        names.extend(tool::ALL.iter().map(|m| m.logo));
        names.extend(majik_providers::ProviderRegistry::shared().all().iter().map(|d| d.logo_asset_name));
        for name in names {
            assert!(Assets::get(&format!("logos/{name}.svg")).is_some(), "logos/{name}.svg is missing");
        }
    }

    /// Logos are drawn as a mask filled with the theme's foreground, like icons, so the same file
    /// serves both themes. A colour in the file would be silently ignored — a white cut-out
    /// becomes solid — so a logo carries none.
    #[test]
    fn logos_are_monochrome() {
        for (path, svg) in logo_svgs() {
            let coloured = ["fill=\"#", "fill:#", "stroke=\"#", "stroke:#", "fill=\"black", "fill=\"white"];
            assert!(!coloured.iter().any(|c| svg.contains(c)), "{path} names a colour; leave fills unset (or currentColor)");
        }
    }

    /// gpui fits an SVG to its box's width and lets the height follow, so a drawing taller than
    /// wide overflows the logo tile. Pad the viewBox to a square instead.
    #[test]
    fn logos_are_no_taller_than_wide() {
        for (path, svg) in logo_svgs() {
            let view_box = svg.split("viewBox=\"").nth(1).and_then(|rest| rest.split('"').next()).unwrap_or_else(|| panic!("{path} has no viewBox"));
            let dims: Vec<f32> = view_box.split_whitespace().map(|n| n.parse().expect("a number")).collect();
            assert_eq!(dims.len(), 4, "{path}: viewBox {view_box:?}");
            assert!(dims[2] >= dims[3], "{path} is taller ({}) than wide ({}): pad its viewBox to a square", dims[3], dims[2]);
        }
    }

    /// Icon names that reach `ui::icon` through an enum rather than a literal at the call site.
    #[test]
    fn role_recovery_and_settings_icons_resolve() {
        for role in AssetRole::ALL {
            assert!(embedded(role.icon()), "{role:?} → {}", role.icon());
        }
        for action in [RecoveryAction::Retry, RecoveryAction::OpenProviderSettings, RecoveryAction::CheckCredits(String::new())] {
            assert!(embedded(action.icon()), "{action:?} → {}", action.icon());
        }
        for page in SettingsPage::ALL {
            assert!(embedded(page.icon()), "{page:?} → {}", page.icon());
        }
        for tab in ComposeTab::ALL {
            assert!(embedded(tab.icon()), "{tab:?} → {}", tab.icon());
        }
        for layout in crate::config::GridLayout::ALL {
            assert!(embedded(layout.icon()), "{layout:?} → {}", layout.icon());
        }
    }
}
